config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'home/index'
  root "home#index"

  get 'home/dice'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
  end

  def dice
      if !user_signed_in?
        redirect_to new_user_session_path
      else
    @random_dice1_result = "dice#{Die.new(6).roll}"
    @random_dice2_result = "dice#{Die.new(6).roll}"
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%=link_to "HOME", root_path, class:"navbar-brand"%>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <%if user_signed_in?%>
         <li class="nav-item">
           <%=link_to "Log  out",  destroy_user_session_path,:method => :delete,class:"nav-link active"%>
          </li>
         <li class="nav-item">
         
          <%=link_to "Edit User",  edit_user_registration_path,class:"nav-link"%>
        </li>
        <% else %>
        <li class="nav-item">
           <%=link_to "Log  in",  new_user_session_path,class:"nav-link active"%>
        </li>
        <li class="nav-item">
  
           <%=link_to "Sign  up",  new_user_registration_path,class:"nav-link"%>
        </li>
        <%end%>

      </ul>
    </div>
  </div>
</nav>

app/views/home/dice.html.erb
<br><br><br><br><br><br><br><br><br><br>
<div class="text-center">
  <div id="loader"></div>
  <div id="wrapper">
    <div id="container">
      <div class="dice-wrapper">
        <%= render(DiceComponent.new(did: 'die-1', random_dice_result: @random_dice1_result)) do %>
        <% end %>
        <%= render(DiceComponent.new(did: 'die-2', random_dice_result: @random_dice2_result)) do %>
        <% end %>
      </div>
      <p id="total"></p>
      <%=link_to "ROLL!!!", home_dice_path ,class:"button"%>
    </div>
  </div>
  <br><br><br><br><br>
</div>

app/views/home/index.html.erb
<%= stylesheet_link_tag "color"%>

<h1 class="display-1 text-center">
  DIGITAL
  <small class="text-muted">DICE</small>
</h1>
<br>
<div class="d-flex justify-content-start">
<div class="card float-left" style="width: 18rem;">
 <%=image_tag 'game1',class:"card-img-top" %>
  <div class="card-body">
    <h5 class="card-title">PLAY</h5>
    <p class="card-text">Can't find your dice? Don't worry, you can still play your favourite board games using Digital Dice. Sign In to use dice.</p>
    <%=link_to "Dice", home_dice_path,class:"btn btn-primary" %>
  </div>
</div>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application"%>
    <%= javascript_importmap_tags %>
    <title>Digital_Dice</title>
  </head>
  <body>
  

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    
    <%=render "home/header"%>

    <div class="container">
    <%if notice%>
    <%=render "layouts/alerts"%>
    <%end%>
    
    <%= yield %>
    </div>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>